name: lfd-book-env
channels:
- conda-forge
- defaults
dependencies:
- python
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- ipywidgets
- nbdime
- emcee
- corner
- scikit-learn
- scikit-image
- pymc3
- jupytext
- pip
- pip:
  - prettyplease
  - tensorflow
  - jupyter-book
  - myst-nb
  - sphinx-proof
  - sphinx-inline-tabs
  - sphinx-exercise
